-- Count of public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_PUBLIC_NODES
WHERE
    TYPE = 2;


-- Count of public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;


-- Count of public projects created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;


-- Count of non-public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_NON_PUBLIC_NODES
WHERE
    TYPE = 2;


-- Count of non-public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;


-- Count of non-public projects created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;


-- ------ Since last audit ------

-- Count of public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_PUBLIC_NODES
WHERE
    TYPE = 2 AND
    CREATED_ON > '2013-11-01 00:00:00' AND
    CREATED_ON < '2014-02-01 00:00:00';


-- Count of public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2 AND
    NODES.CREATED_ON > '2013-11-01 00:00:00' AND
    NODES.CREATED_ON < '2014-02-01 00:00:00';


-- Count of public projects created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2 AND
    NODES.CREATED_ON > '2013-11-01 00:00:00' AND
    NODES.CREATED_ON < '2014-02-01 00:00:00';


-- Count of non-public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_NON_PUBLIC_NODES
WHERE
    TYPE = 2 AND
    CREATED_ON > '2013-11-01 00:00:00' AND
    CREATED_ON < '2014-02-01 00:00:00';


-- Count of non-public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2 AND
    NODES.CREATED_ON > '2013-11-01 00:00:00' AND
    NODES.CREATED_ON < '2014-02-01 00:00:00';


-- Count of non-public projects created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2 AND
    NODES.CREATED_ON > '2013-11-01 00:00:00' AND
    NODES.CREATED_ON < '2014-02-01 00:00:00';
