-- file_counts_snapshot_20141101.txt

-- Count of public files
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_PUBLIC_NODES NODES
WHERE
    TYPE = 16
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_DAEMON_USERS)
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_TEST_USERS);


-- Count of public files created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16;


-- Count of public files created by Sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16;


-- Count of non-public files
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES
WHERE
    TYPE = 16
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_DAEMON_USERS)
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_TEST_USERS);


-- Count of non-public files created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16;


-- Count of non-public files created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16;


-- ------ Since last audit ------

-- Count of public files
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_PUBLIC_NODES NODES
WHERE
    TYPE = 16 AND
    CREATED_ON > '2014-08-01 00:00:00' AND
    CREATED_ON < '2014-11-01 00:00:00'
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_DAEMON_USERS)
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_TEST_USERS);


-- Count of public files created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16 AND
    NODES.CREATED_ON > '2014-08-01 00:00:00' AND
    NODES.CREATED_ON < '2014-11-01 00:00:00';


-- Count of public files created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16 AND
    NODES.CREATED_ON > '2014-08-01 00:00:00' AND
    NODES.CREATED_ON < '2014-11-01 00:00:00';


-- Count of non-public files
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES
WHERE
    TYPE = 16 AND
    CREATED_ON > '2014-08-01 00:00:00' AND
    CREATED_ON < '2014-11-01 00:00:00'
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_DAEMON_USERS)
    AND NODES.CREATED_BY NOT IN (SELECT ID FROM AUDIT_TEST_USERS);


-- Count of non-public files created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16 AND
    NODES.CREATED_ON > '2014-08-01 00:00:00' AND
    NODES.CREATED_ON < '2014-11-01 00:00:00';


-- Count of non-public files created by sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 16 AND
    NODES.CREATED_ON > '2014-08-01 00:00:00' AND
    NODES.CREATED_ON < '2014-11-01 00:00:00';
