-- Active Sage users
-- active_sage_users.csv
SELECT
    USERS.ID AS USER_ID,
    USERS.EMAIL AS EMAIL,
    COUNT(DISTINCT UAD.MONTH, UAD.DAY) AS DAYS
FROM
    AUDIT_SAGE_USERS USERS,
    AUDIT_ACTIVE_USERS AU,
    AUDIT_USER_ACTIVE_DAYS UAD
WHERE
    USERS.ID = AU.USER_ID AND
    AU.USER_ID = UAD.USER_ID
GROUP BY
    USERS.ID,
    USERS.EMAIL
ORDER BY
    DAYS DESC;

-- Active non-Sage users
-- active_non_sage_users.csv
SELECT
    USERS.ID AS USER_ID,
    USERS.EMAIL AS EMAIL,
    COUNT(DISTINCT UAD.MONTH, UAD.DAY) AS DAYS
FROM
    AUDIT_NON_SAGE_USERS USERS,
    AUDIT_ACTIVE_USERS AU,
    AUDIT_USER_ACTIVE_DAYS UAD
WHERE
    USERS.ID = AU.USER_ID AND
    AU.USER_ID = UAD.USER_ID
GROUP BY
    USERS.ID,
    USERS.EMAIL
ORDER BY
    DAYS DESC;



-- Active daemon users
-- active_daemon_users.csv
SELECT
    USERS.ID AS USER_ID,
    USERS.EMAIL AS EMAIL,
    COUNT(DISTINCT UAD.MONTH, UAD.DAY) AS DAYS
FROM
    AUDIT_DAEMON_USERS USERS,
    AUDIT_ACTIVE_USERS AU,
    AUDIT_USER_ACTIVE_DAYS UAD
WHERE
    USERS.ID = AU.USER_ID AND
    AU.USER_ID = UAD.USER_ID
GROUP BY
    USERS.ID,
    USERS.EMAIL
ORDER BY
    DAYS DESC;
