SELECT
    NSU.ID AS USER_ID,
    NSU.EMAIL AS USER_EMAIL,
    AR.USER_AGENT AS CLIENT,
    COUNT(DISTINCT AR.SESSION) AS SESSION_COUNT
FROM
    AUDIT_ACCESS_RECORDS AR,
    AUDIT_NON_SAGE_USERS NSU
WHERE
    AR.USER_ID = NSU.ID AND
    AR.USER_ID IN (297328, 1528703, 363879, 1867663, 375805)
GROUP BY
    USER_ID,
    USER_EMAIL,
    CLIENT
ORDER BY
    USER_ID,
    SESSION_COUNT DESC;