-- Public, controlled files
SELECT
    F.ID AS ID,
    F.NAME AS FILE_NAME,
    F.PROJECT_ID AS PROJECT_ID,
    PNP.NAME AS PROJECT_NAME
FROM
    AUDIT_FILES F,
    AUDIT_PUBLIC_NODES PN,
    AUDIT_PUBLIC_NODES PNP,
    AUDIT_CONTROLLED C
WHERE
    F.ID = PN.ID
AND
    F.PROJECT_ID = PNP.ID
AND
    F.ID = C.ID;


-- Public, restricted files
SELECT
    F.ID AS ID,
    F.NAME AS FILE_NAME,
    F.PROJECT_ID AS PROJECT_ID,
    PNP.NAME AS PROJECT_NAME
FROM
    AUDIT_FILES F,
    AUDIT_PUBLIC_NODES PN,
    AUDIT_PUBLIC_NODES PNP,
    AUDIT_RESTRICTED R
WHERE
    F.ID = PN.ID
AND
    F.PROJECT_ID = PNP.ID
AND
    F.ID = R.ID;