-- Count of public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_PUBLIC_NODES
WHERE
    TYPE = 2;


-- Count of public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;


-- Count of non-public projects
SELECT
    COUNT(DISTINCT ID)
FROM
    AUDIT_NON_PUBLIC_NODES
WHERE
    TYPE = 2;


-- Count of non-public projects created by non-sage users
SELECT
    COUNT(DISTINCT NODES.ID)
FROM
    AUDIT_NON_PUBLIC_NODES NODES,
    AUDIT_NON_SAGE_USERS USERS
WHERE
    NODES.CREATED_BY = USERS.ID AND
    NODES.TYPE = 2;
