-- File downloads of selected users
SELECT
    NSU.ID AS USER_ID,
    NSU.EMAIL AS USER_EMAIL,
    FILES.ID AS FILE_ID,
    FILES.NAME AS FILE_NAME,
    COUNT(DISTINCT AR.SESSION) AS SESSION_COUNT,
    FILES.ID IN (SELECT ID FROM AUDIT_CONTROLLED) AS CONTROLLED,
    FILES.ID IN (SELECT ID FROM AUDIT_RESTRICTED) AS RESTRICTED
FROM
    AUDIT_ACCESS_RECORDS AR,
    AUDIT_NON_SAGE_USERS NSU,
    AUDIT_FILES FILES
WHERE
    AR.USER_ID = NSU.ID AND
    AR.ENTITY_ID = FILES.ID AND
    AR.USER_ID IN (2224165, 273956, 1961122, 3319762, 273967) AND
    AR.METHOD = 'GET' AND
    AR.URI REGEXP '^/repo/v1/entity/syn[0-9]+(/version/[0-9]+)?/file$'
GROUP BY
    USER_ID,
    USER_EMAIL,
    FILE_ID,
    FILE_NAME
ORDER BY
    USER_ID,
    SESSION_COUNT DESC;
