SELECT
    NSU.ID AS USER_ID,
    NSU.EMAIL AS USER_EMAIL,
    FILES.ID AS FILE_ID,
    FILES.NAME AS FILE_NAME,
    COUNT(DISTINCT AR.SESSION) AS SESSION_COUNT
FROM
    AUDIT_ACCESS_RECORDS AR,
    AUDIT_NON_SAGE_USERS NSU,
    AUDIT_FILES FILES
WHERE
    AR.USER_ID = NSU.ID AND
    AR.ENTITY_ID = FILES.ID AND
    AR.USER_ID IN (297328, 1528703, 363879, 1867663, 375805) AND
    AR.URI REGEXP '^/repo/v1/entity/syn[0-9]+(/version/[0-9]+)?/file$'
GROUP BY
    USER_ID,
    USER_EMAIL,
    FILE_ID,
    FILE_NAME
ORDER BY
    USER_ID,
    SESSION_COUNT DESC;