-- Public files uploaded by non-sage users during the last audit quarter
-- public_file_uploads_non_sage_current_audit_period.csv
CREATE TABLE file_upload_non_sage SELECT DISTINCT
    FILES.ID AS FILE_ID,
    FILES.NAME AS FILE_NAME,
    FILES.CREATED_ON AS FILE_CREATED_ON,
    NON_SAGE_USERS.EMAIL AS FILE_CREATED_BY,
    FILES.PROJECT_ID AS PROJECT_ID,
    PROJ_NODES.NAME AS PROJECT_NAME,
    PROJ_NODES.ID IN (SELECT ID FROM AUDIT_PUBLIC_NODES) AS IS_PROJECT_PUBLIC,
    PA.ALIAS_DISPLAY AS PROJECT_CREATED_BY,
    FILES.ID IN (SELECT ID FROM AUDIT_CONTROLLED) AS CONTROLLED,
    FILES.ID IN (SELECT ID FROM AUDIT_RESTRICTED) AS RESTRICTED
FROM
    AUDIT_FILES FILES
    JOIN AUDIT_PUBLIC_NODES FILE_NODES ON FILES.ID = FILE_NODES.ID
    JOIN JDONODE PROJ_NODES ON FILES.PROJECT_ID = PROJ_NODES.ID
    JOIN AUDIT_NON_SAGE_USERS NON_SAGE_USERS ON FILES.CREATED_BY = NON_SAGE_USERS.ID
    JOIN JDOUSERGROUP UG ON PROJ_NODES.CREATED_BY = UG.ID
    JOIN PRINCIPAL_ALIAS PA ON UG.ID = PA.PRINCIPAL_ID 
WHERE
    PA.TYPE = 'USER_EMAIL' AND
    FILES.CREATED_ON > '2015-05-01 00:00:00' AND
    FILES.CREATED_ON < '2015-08-01 00:00:00'
ORDER BY
    FILES.PROJECT_ID;

select * FROM file_upload_non_sage group by FILE_ID;


-- Public files uploaded by sage users during the last audit quarter
-- public_file_uploads_sage_current_audit_period.csv
CREATE TABLE file_upload_sage SELECT DISTINCT
    FILES.ID AS FILE_ID,
    FILES.NAME AS FILE_NAME,
    FILES.CREATED_ON AS FILE_CREATED_ON,
    SAGE_USERS.EMAIL AS FILE_CREATED_BY,
    FILES.PROJECT_ID AS PROJECT_ID,
    PROJ_NODES.NAME AS PROJECT_NAME,
    PROJ_NODES.ID IN (SELECT ID FROM AUDIT_PUBLIC_NODES) AS IS_PROJECT_PUBLIC,
    PA.ALIAS_DISPLAY AS PROJECT_CREATED_BY,
    FILES.ID IN (SELECT ID FROM AUDIT_CONTROLLED) AS CONTROLLED,
    FILES.ID IN (SELECT ID FROM AUDIT_RESTRICTED) AS RESTRICTED
FROM
    AUDIT_FILES FILES
    JOIN AUDIT_PUBLIC_NODES FILE_NODES ON FILES.ID = FILE_NODES.ID
    JOIN JDONODE PROJ_NODES ON FILES.PROJECT_ID = PROJ_NODES.ID
    JOIN AUDIT_SAGE_USERS SAGE_USERS ON FILES.CREATED_BY = SAGE_USERS.ID
    JOIN JDOUSERGROUP UG ON PROJ_NODES.CREATED_BY = UG.ID
    JOIN PRINCIPAL_ALIAS PA ON UG.ID = PA.PRINCIPAL_ID 
WHERE
    PA.TYPE = 'USER_EMAIL' AND
    FILES.CREATED_ON > '2015-05-01 00:00:00' AND
    FILES.CREATED_ON < '2015-08-01 00:00:00'
ORDER BY
    FILES.PROJECT_ID;

select * FROM file_upload_sage group by FILE_ID;

-- Public tables uploaded by non-sage users during the last audit quarter
-- public_table_uploads_non_sage_current_audit_period.csv
CREATE TABLE table_upload_non_sage SELECT DISTINCT
    TABLES.ID AS TABLE_ID,
    TABLES.NAME AS TABLE_NAME,
    TABLES.CREATED_ON AS TABLE_CREATED_ON,
    NON_SAGE_USERS.EMAIL AS TABLE_CREATED_BY,
    TABLES.PROJECT_ID AS PROJECT_ID,
    PROJ_NODES.NAME AS PROJECT_NAME,
    PROJ_NODES.ID IN (SELECT ID FROM AUDIT_PUBLIC_NODES) AS IS_PROJECT_PUBLIC,
    PA.ALIAS_DISPLAY AS PROJECT_CREATED_BY,
    TABLES.ID IN (SELECT ID FROM AUDIT_CONTROLLED) AS CONTROLLED,
    TABLES.ID IN (SELECT ID FROM AUDIT_RESTRICTED) AS RESTRICTED
FROM
    AUDIT_TABLES TABLES
    JOIN AUDIT_PUBLIC_NODES TABLE_NODES ON TABLES.ID = TABLE_NODES.ID
    JOIN JDONODE PROJ_NODES ON TABLES.PROJECT_ID = PROJ_NODES.ID
    JOIN AUDIT_NON_SAGE_USERS NON_SAGE_USERS ON TABLES.CREATED_BY = NON_SAGE_USERS.ID
    JOIN JDOUSERGROUP UG ON PROJ_NODES.CREATED_BY = UG.ID
    JOIN PRINCIPAL_ALIAS PA ON UG.ID = PA.PRINCIPAL_ID 
WHERE
    PA.TYPE = 'USER_EMAIL' AND
    TABLES.CREATED_ON > '2015-05-01 00:00:00' AND
    TABLES.CREATED_ON < '2015-08-01 00:00:00'
ORDER BY
    TABLES.PROJECT_ID;

select * FROM table_upload_non_sage group by TABLE_ID;


-- Public tables uploaded by sage users during the last audit quarter
-- public_table_uploads_sage_current_audit_period.csv
CREATE TABLE table_upload_sage SELECT DISTINCT
    TABLES.ID AS TABLE_ID,
    TABLES.NAME AS TABLE_NAME,
    TABLES.CREATED_ON AS TABLE_CREATED_ON,
    SAGE_USERS.EMAIL AS TABLE_CREATED_BY,
    TABLES.PROJECT_ID AS PROJECT_ID,
    PROJ_NODES.NAME AS PROJECT_NAME,
    PROJ_NODES.ID IN (SELECT ID FROM AUDIT_PUBLIC_NODES) AS IS_PROJECT_PUBLIC,
    PA.ALIAS_DISPLAY AS PROJECT_CREATED_BY,
    TABLES.ID IN (SELECT ID FROM AUDIT_CONTROLLED) AS CONTROLLED,
    TABLES.ID IN (SELECT ID FROM AUDIT_RESTRICTED) AS RESTRICTED
FROM
    AUDIT_TABLES TABLES
    JOIN AUDIT_PUBLIC_NODES TABLE_NODES ON TABLES.ID = TABLE_NODES.ID
    JOIN JDONODE PROJ_NODES ON TABLES.PROJECT_ID = PROJ_NODES.ID
    JOIN AUDIT_SAGE_USERS SAGE_USERS ON TABLES.CREATED_BY = SAGE_USERS.ID
    JOIN JDOUSERGROUP UG ON PROJ_NODES.CREATED_BY = UG.ID
    JOIN PRINCIPAL_ALIAS PA ON UG.ID = PA.PRINCIPAL_ID 
WHERE
    PA.TYPE = 'USER_EMAIL' AND
    TABLES.CREATED_ON > '2015-05-01 00:00:00' AND
    TABLES.CREATED_ON < '2015-08-01 00:00:00'
ORDER BY
    TABLES.PROJECT_ID;

select * FROM table_upload_sage group by TABLE_ID;
