-- Projects accessed by selected users
-- user_details_projects.csv
SELECT
    NSU.ID AS USER_ID,
    NSU.EMAIL AS USER_EMAIL,
    BENEFACTORS.ID AS PROJECT_ID,
    BENEFACTORS.NAME AS PROJECT_NAME,
    COUNT(DISTINCT AR.SESSION) AS SESSION_COUNT
FROM
    AUDIT_ACCESS_RECORDS AR,
    AUDIT_NON_SAGE_USERS NSU,
    JDONODE NODES,
    JDONODE BENEFACTORS
WHERE
    AR.USER_ID = NSU.ID AND
    AR.ENTITY_ID = NODES.ID AND
    NODES.BENEFACTOR_ID = BENEFACTORS.ID AND
    AR.USER_ID IN (1586613, 3319668, 3321844, 3319406, 3321882, 3323064, 3320967, 3322446)
GROUP BY
    USER_ID,
    USER_EMAIL,
    PROJECT_ID,
    PROJECT_NAME
ORDER BY
    USER_ID,
    SESSION_COUNT DESC;
