CREATE TABLE ACCESS_RECORD (
    OBJECT_ID VARCHAR(12),
    ENTITY_ID BIGINT,
    LATENCY BIGINT,
    TIMESTAMP_TEMP BIGINT,    -- Import as long integers first
    TIMESTAMP DATETIME,       -- Then convert to date time
    USER_AGENT VARCHAR(256),
    SESSION CHAR(36),
    URI VARCHAR(256),
    USER_ID_TEMP VARCHAR(12), -- Import as strings (as some are empty strings)
    USER_ID INT,              -- Then convert to integers
    METHOD VARCHAR(12),
    STACK INT,
    SUCCESS VARCHAR(5)
);


-- Imports merged access-record files of selected columns
-- 21,731,753 rows. Took 88 minutes on a medium instance
LOAD DATA LOCAL INFILE
    '/Users/ewu/Documents/logs/2014-02-audit/results/access-record-lean.csv' 
INTO TABLE
    ACCESS_RECORD
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n' (
    OBJECT_ID,
    LATENCY,
    TIMESTAMP_TEMP,
    USER_AGENT,
    SESSION,
    URI,
    USER_ID_TEMP,
    METHOD,
    STACK,
    SUCCESS
);


-- Converts imported columns to proper types and values
UPDATE ACCESS_RECORD SET TIMESTAMP = FROM_UNIXTIME(TIMESTAMP_TEMP / 1000);
UPDATE ACCESS_RECORD SET USER_ID = CAST(USER_ID_TEMP AS UNSIGNED) WHERE USER_ID_TEMP IS NOT NULL AND USER_ID_TEMP <> '';
UPDATE ACCESS_RECORD SET ENTITY_ID = CAST(SUBSTRING(OBJECT_ID, 4) AS UNSIGNED) WHERE OBJECT_ID LIKE 'syn%';


-- Adds indices
ALTER TABLE ACCESS_RECORD ADD INDEX USING BTREE (TIMESTAMP);
ALTER TABLE ACCESS_RECORD ADD INDEX USING HASH (USER_ID);
ALTER TABLE ACCESS_RECORD ADD INDEX USING HASH (ENTITY_ID);
ALTER TABLE ACCESS_RECORD ADD INDEX USING HASH (SESSION);
