CREATE TABLE AUDIT_RESTRICTED AS
SELECT DISTINCT
    NAR.SUBJECT_ID AS ID
FROM
    NODE_ACCESS_REQUIREMENT NAR,
    ACCESS_REQUIREMENT AR,
    JDONODE NODE
WHERE
    NAR.REQUIREMENT_ID = AR.ID AND
    NAR.SUBJECT_ID = NODE.ID AND
    AR.ENTITY_TYPE = 'org.sagebionetworks.repo.model.TermsOfUseAccessRequirement' AND
    NODE.BENEFACTOR_ID <> 1681355;

ALTER TABLE AUDIT_RESTRICTED ADD INDEX USING HASH (ID);


CREATE TABLE AUDIT_CONTROLLED AS
SELECT DISTINCT
    NAR.SUBJECT_ID AS ID
FROM
    NODE_ACCESS_REQUIREMENT NAR,
    ACCESS_REQUIREMENT AR,
    JDONODE NODE
WHERE
    NAR.REQUIREMENT_ID = AR.ID AND
    NAR.SUBJECT_ID = NODE.ID AND
    AR.ENTITY_TYPE = 'org.sagebionetworks.repo.model.ACTAccessRequirement' AND 
    NODE.PARENT_ID <> 1681355;

ALTER TABLE AUDIT_CONTROLLED ADD INDEX USING HASH (ID);
