-- File entities and their containing project
CREATE TABLE AUDIT_TABLES AS
SELECT DISTINCT
    NODE.ID AS ID,
    NODE.NAME AS NAME,
    FROM_UNIXTIME(NODE.CREATED_ON / 1000) AS CREATED_ON,
    NODE.CREATED_BY AS CREATED_BY,
    NODE.PROJECT_ID AS PROJECT_ID
FROM
    JDONODE NODE
WHERE
    NODE.NODE_TYPE = 'table' AND
    NODE.BENEFACTOR_ID <> 1681355; -- Not in trash can

-- Adds indices
ALTER TABLE AUDIT_TABLES ADD INDEX USING HASH (ID);
ALTER TABLE AUDIT_TABLES ADD INDEX USING BTREE (CREATED_ON);
ALTER TABLE AUDIT_TABLES ADD INDEX USING HASH (CREATED_BY);
ALTER TABLE AUDIT_TABLES ADD INDEX USING HASH (PROJECT_ID);


