-- Nodes, public or private
CREATE OR REPLACE VIEW VIEW_NODES AS
SELECT
    NODE.ID AS ID,
    NODE.NODE_TYPE AS TYPE,
    NODE.NAME AS NAME,
	(UG.ID = 273949 AND RAAT.STRING_ELE = 'READ') AS IS_PUBLIC, -- If the anonymous user group can read
    NODE.CREATED_ON AS CREATED_ON,
    NODE.CREATED_BY AS CREATED_BY,
	NODE.PARENT_ID AS PARENT_ID,
    NODE.BENEFACTOR_ID AS BENEFACTOR_ID
FROM
    ACL,
    JDONODE NODE,
    JDONODE BNODE,
    JDOUSERGROUP UG,
    JDORESOURCEACCESS RA,
    JDORESOURCEACCESS_ACCESSTYPE RAAT
WHERE
    NODE.BENEFACTOR_ID = BNODE.ID AND
    ACL.ID = BNODE.ID AND
    UG.ID = RA.GROUP_ID AND
    RA.OWNER_ID = ACL.ID AND
    RAAT.OWNER_ID = ACL.ID AND
    RA.ID = RAAT.ID_OID AND
    NODE.BENEFACTOR_ID <> 1681355; -- Not in trash can


-- Unit tests
SELECT CONCAT(CASE WHEN
    (SELECT COUNT(DISTINCT ID) FROM VIEW_NODES WHERE IS_PUBLIC IS TRUE) > 50000 AND
    (SELECT COUNT(DISTINCT ID) FROM VIEW_NODES WHERE IS_PUBLIC IS TRUE) < 500000
    THEN 'PASSED' ELSE 'FAILED' END,
    ' -- More than 5000 public entites.');

SELECT CONCAT(CASE WHEN
    (SELECT COUNT(DISTINCT ID) FROM VIEW_NODES WHERE IS_PUBLIC IS FALSE) > 900000
    THEN 'PASSED' ELSE 'FAILED' END,
    ' -- The majority are private entites.');
